apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: "2023-07-24T21:06:23Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    type: local
  name: token-file
  resourceVersion: "289713"
  uid: 97eebd36-e313-4b75-89a7-533cb77fbaff
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /users/vishalt/Documents/kubernetes/token
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
status:
  phase: Available
